### ISSUE TITLE
gpg key is not trusted

### ISSUE THREAD

**Issue by haheute** [daniellandau/AUR-thunderbird-enigmail#2]
I importet the new gpg key with `gpg --recv-keys 9369CDF3
`
but get a message, that the key is not trusted and update of thunderbird-enigmail stops.

```
 ==> Überprüfe Signaturen der Quell-Dateien mit gpg...
    enigmail-1.7.2.tar.gz ... FEHLGESCHLAGEN (Dem öffentlichen Schlüssel 10B2E4A0E718BB1B2791DAC4F040E41B9369CDF3 wird nicht vertraut)
```

what should I do?

**Comment by daniellandau** [comment]
You can do one of the following:

    $ makepkg --skippgpcheck

or

    $ gpg --recv-keys 9369CDF3
    $ gpg --edit-key 9369CDF3 trust quit # answer prompts
    $ makepkg
